(import srfi-1)
(import srfi-69)
(load "compiler.ss")

(define tests 0)
(define passed 0)
(define (exec-test got out expr)
  (set! tests (+ tests 1))
  (if (not (equal? got out))
    (print "expecting " expr 
         "\n    to be " out 
         "\n  but got " got)
    (set! passed (+ passed 1))))

(define-syntax test-case
  (syntax-rules ()
    [(_ expr expect) (exec-test expr expect 'expr)]))

(test-case (closures->currying '1 '())                            '1)
(test-case (closures->currying 'a '())                            'a)
(test-case (closures->currying '(begin a) '())                    '(begin a))
(test-case (closures->currying '(lambda (x) x) '())               '(lambda (x) x))
(test-case (closures->currying '(lambda (x) y) '(y))              '(curry (lambda (y x) y) y))
(test-case (closures->currying '(let ((y 1)) (lambda (x) y)) '()) '(let ((y 1)) (curry (lambda (y x) y) y)))

(test-case (mutation->boxing 'a '())                                     'a)
(test-case (mutation->boxing '1 '())                                     '1)
(test-case (mutation->boxing '(f a) '())                                 '(f a))
(test-case (mutation->boxing '(begin a) '())                             '(begin a))
(test-case (mutation->boxing '(set! a 1) '())                            '(set! a 1))
(test-case (mutation->boxing '(let ((a 1)) (lambda (a) (set! a 2))) '()) '(let ((a 1)) (lambda (a) (set! a 2))))
(test-case (mutation->boxing '(let ((a 1)) (lambda () (set! a 2))) '())  '(let ((a 1)) (set! a (make-box a)) (lambda () (box-set! a 2))))

(test-case (slots-needed 'a)                                       0)
(test-case (slots-needed '(f a))                                   0)
(test-case (slots-needed '(let ((x 1))))                           1)
(test-case (slots-needed '(let ((x (let ((y 2))))) y))             1)
(test-case (slots-needed '(let ((w 0) (x (let ((y 2) (w 3))))) y)) 3)
(test-case (slots-needed '(let ((w 0)) (let ((y 2) (w 3)) y)))     3)

(define vn 0)
(set! anf-gensym (lambda () 
                   (set! vn (+ vn 1))
                   (string->symbol (string-append "v" (number->string vn)))))

(test-case (expr->anf '1) '1)
(test-case (expr->anf 'a) 'a)
(test-case (expr->anf '(f x)) '(f x))
(test-case (expr->anf '(f (lambda () 1))) '(f (lambda () 1)))
(test-case (expr->anf '(f (g x))) '(let ((v1 (g x))) (f v1)))
(test-case (expr->anf '(f (let ((g x)) g))) '(let ((v2 (let ((g x)) g))) (f v2)))

(define test-package (make-package '() '() 0 '()))
(define b (make-block 0 0 '()))
(test-case (package-value! test-package 'a) 0)
(test-case (package-value! test-package 'b) 1)
(test-case (package-value! test-package 'c) 2)
(test-case (package-value! test-package 'a) 0)
(test-case (package-block! test-package b) 0)
(test-case (package-block! test-package b) 1)

(test-case (expr->instructions '1 (make-scope test-package '() #f 0)) 
           '((value 3)))
(test-case (expr->instructions 'a (make-scope test-package '() #f 0)) 
           '((global-get 0)))
(test-case (expr->instructions 'a (make-scope test-package '(a) #f 0))
           '((local-get 0)))
(test-case (expr->instructions 'b (make-scope test-package '(a b) #f 0))
           '((local-get 1)))
(test-case (expr->instructions '(begin) (make-scope test-package '(a) #f 0))
           '((void)))
(test-case (expr->instructions '(begin a) (make-scope test-package '(a) #f 0))
           '((local-get 0)))
(test-case (expr->instructions '(if a 1 2) (make-scope test-package '(a) #f (box 0))) 
           '((local-get 0) (branch 0) (value 3) (jump 1) (point 0) (value 4) (point 1)))
(test-case (expr->instructions '(set! a 2) (make-scope test-package '(a) #f (box 0))) 
           '((value 4) (local-set 0) (void)))
(test-case (expr->instructions '(set! a 2) (make-scope test-package '() #f (box 0)))
           '((value 4) (global-set 0) (void)))
(test-case (expr->instructions '(lambda ()) (make-scope test-package '() #f (box 0)))
           '((block 2)))
(test-case (expr->instructions '(let ([a 1]) a) (make-scope test-package '() #f (box 0)))
           '((value 3) (local-set 0) (local-get 0)))
(test-case (expr->instructions '(let ([a 1] [b 2]) a) (make-scope test-package '() #f (box 0)))
           '((value 3) (local-set 0) (value 4) (local-set 1) (local-get 0)))
(test-case (expr->instructions '(let ([a 1] [b (let ([x 2]) x)]) a) (make-scope test-package '() #f (box 0)))
           '((value 3) (local-set 0) (value 4) (local-set 1) (local-get 1) (local-set 1) (local-get 0)))
(test-case (expr->instructions '(let ([a 1] [b (let ([x 2]) x)]) a) (make-scope test-package '() #t (box 0)))
           '((value 3) (local-set 0) (value 4) (local-set 1) (local-get 1) (local-set 1) (local-get 0) (return)))
(test-case (expr->instructions '(f x) (make-scope test-package '(x) #f (box 0)))
           '((global-get 1) (local-get 0) (call 0) (point 0)))
(test-case (expr->instructions '(f x) (make-scope test-package '(x) #t (box 0)))
           '((global-get 1) (local-get 0) (return-call)))

(print "tests: " tests ", passed: " passed)

